### ISSUE TITLE
linker error

### ISSUE THREAD

**Issue by yaizudamashii** [BayPhillips/compatible-alert-controller#3]
I could not compile the demo project.
Steps to reproduce.
1. download zip from https://github.com/BayPhillips/compatible-alert-controller/archive/master.zip
2. unzip into /Users/<username>/Developer folder
3. navigate to /Users/<username>/kDeveloper/compatible-alert-controller-master/BPCompatibleAlertControllerDemo
4. double click on BPCompatibleAlertControllerDemo.xcodeproj
5. select a simulator and press run in xcode

I get the following build error
ld: file not found: /Users/<username>/Library/Developer/Xcode/DerivedData/BPCompatibleAlertControllerDemo-dakohkknawpcjndqdoakidbexzhz/Build/Products/Debug-iphonesimulator/CompatibleAlertControllerDemo.app/CompatibleAlertControllerDemo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BayPhillips** [comment]
Hi @yaizudamashii. That's really weird as that wasn't happening before! I'll take a look tomorrow and get this fixed. Thanks for the heads up.

**Comment by BayPhillips** [comment]
Looks like there was an old build setting. Probably back from 6.0 or 6.1 that was no longer needed. Fixed in be89c6df7b8157921ae02674d25d646454e8249b . Thanks for the issue!
